### ISSUE TITLE
Traceback when executing in python 3.6.8

### ISSUE THREAD

**Issue by waldirio** [waldirio/rvtools_python#42]
```
# ./dist/rvtools 
Reading Conf File
There isn't the conf file on ~/.rvtools.conf, creating a new one now
according to the example below:
-----------------------
vcenter=<fqdn>
username=<vcenter username>
password=<password>
directory=<directory>
-----------------------

Please update the info if you would like to persist the credentials
Traceback (most recent call last):
  File "rvtools", line 10, in <module>
  File "rvtools/rvtools.py", line 62, in main
    exit()
NameError: name 'exit' is not defined
[12369] Failed to execute script 'rvtools' due to unhandled exception!
```

**Comment by waldirio** [comment]
Fixed and working as expected.
```
$ ./rvtools 
Reading Conf File
There isn't the conf file on ~/.rvtools.conf, creating a new one now
according to the example below:
-----------------------
vcenter=<fqdn>
username=<vcenter username>
password=<password>
directory=<directory>
-----------------------

Please update the info if you would like to persist the credentials
$ 
```
